SET PASSWORD FOR 'root'@'localhost' = PASSWORD('root');
SET sql_mode = 'NO_ZERO_DATE';

/* Enum: SEX - FEMALE("FEMALE",0), MALE("MALE",1); Enum: ID_NUMBER_TYPE - PASSPORT("PASSPORT",0), IDENTITYCARD("IDENTITY CARD",1) */
INSERT INTO USER(USERNAME,REAL_NAME,ENGLISH_NAME,PASSWORD,SEX,ID_NUMBER,ID_NUMBER_TYPE,CURRENT_COUNTRY,CURRENT_CITY,PORTRAIT,CREATE_TIME,UPDATE_TIME) 
VALUES('email@email.com','Real Name','Cain','password',1,'310229123456789',1,'USA','San Diego','file path',NOW(),null);

/* Enum: TYPE - EMAIL("EMAIL",0), TELEPHONE("TELEPHONE",1), OTHER("OTHER",2) */
/* Enum: STATUS - ACTIVE("ACTIVE",0), INACTIVE("INACTIVE",1) */
INSERT INTO CONTACT(INFO,TYPE,OTHER_DESCRIPTION,STATUS,USER_ID,CREATE_TIME,UPDATE_TIME) VALUES("email@email.com",0,"",0,1,NOW(),null);
INSERT INTO CONTACT(INFO,TYPE,OTHER_DESCRIPTION,STATUS,USER_ID,CREATE_TIME,UPDATE_TIME) VALUES("911",1,"",0,1,NOW(),null);
INSERT INTO CONTACT(INFO,TYPE,OTHER_DESCRIPTION,STATUS,USER_ID,CREATE_TIME,UPDATE_TIME) VALUES("123456",2,"WebChat",0,1,NOW(),null);
INSERT INTO CONTACT(INFO,TYPE,OTHER_DESCRIPTION,STATUS,USER_ID,CREATE_TIME,UPDATE_TIME) VALUES("666666@email.com",0,"",1,1,NOW(),null);
INSERT INTO CONTACT(INFO,TYPE,OTHER_DESCRIPTION,STATUS,USER_ID,CREATE_TIME,UPDATE_TIME) VALUES("6666666",1,"",1,1,NOW(),null);
INSERT INTO CONTACT(INFO,TYPE,OTHER_DESCRIPTION,STATUS,USER_ID,CREATE_TIME,UPDATE_TIME) VALUES("666666",2,"WebChat",1,1,NOW(),null);


/* Enum: UNIVERSITY_DEGREE - Bachelor("BACHELOR",0), Master("MASTER",1), Doctor("DOCTOR",2), PostDoctor("POST-DOCTOR",3), Other("OTHER",4) */
INSERT INTO PERSONAL_HISTORY(UNIVERSITY,UNIVERSITY_DEGREE,MAJOR,GRADUATION_YEAR,USER_ID,CREATE_TIME,UPDATE_TIME)
 VALUES("San Diego State University",2,'Computer Science and Technology','2013',1,NOW(),null);


/* Enum: TYPE - Honorary_Title("HONORARY TITLE",0), Thesis("THESIS",1), Intellectual_property("INTELLECTUAL PROPERTY",2), Other("OTHER",3) */
INSERT INTO AWARD(TYPE,DESCRIPTION,REFERRER,OTHER,USER_ID,CREATE_TIME,UPDATE_TIME) VALUES(0,'Captain','Bill','',1,NOW(),null);




























