/* DDL FOR MySQL DATABASE */

/*CREATE DATABASE IF NOT EXISTS HC;*/

CREATE TABLE USER (
 ID INT(10) AUTO_INCREMENT NOT NULL PRIMARY KEY,
 USERNAME VARCHAR(50) NOT NULL UNIQUE,
 REAL_NAME VARCHAR(50),
 ENGLISH_NAME VARCHAR(50),
 PASSWORD VARCHAR(50),
 SEX INT,
 ID_NUMBER VARCHAR(50),
 ID_NUMBER_TYPE INT,
 CURRENT_COUNTRY VARCHAR(50),
 CURRENT_CITY VARCHAR(50)
)
ENGINE=InnoDB;

CREATE TABLE CONTACT (
 ID INT(10) AUTO_INCREMENT NOT NULL PRIMARY KEY,
 INFO VARCHAR(50),
 TYPE INT,
 OTHER_DESCRIPTION VARCHAR(10),
 USER_ID INT(10)
)
ENGINE=InnoDB;

CREATE TABLE PERSONAL_HISTORY (
 ID INT(10) AUTO_INCREMENT NOT NULL PRIMARY KEY,
 UNIVERSITY VARCHAR(50),
 UNIVERSITY_DEGREE INT,
 GRADUATION_YEAR YEAR(4),
 USER_ID INT(10)
)
ENGINE=InnoDB;


CREATE TABLE AWARDS (
 ID INT(10) AUTO_INCREMENT NOT NULL PRIMARY KEY,
 TYPE INT,
 DESCRIPTION VARCHAR(50),
 REFERRER VARCHAR(50),
 OTHER VARCHAR(50),
 USER_ID INT(10)
)
ENGINE=InnoDB;

/* CONSTRAINT */
ALTER TABLE CONTACT ADD CONSTRAINT USER_ID_CONTACT_FK FOREIGN KEY (USER_ID) REFERENCES USER(ID);
ALTER TABLE PERSONAL_HISTORY ADD CONSTRAINT USER_ID_PERSONAL_HISTORY_FK FOREIGN KEY (USER_ID) REFERENCES USER(ID);
ALTER TABLE AWARDS ADD CONSTRAINT USER_ID_AWARDS_FK FOREIGN KEY (USER_ID) REFERENCES USER(ID);
/* CONSTRAINT */

/* END */




















