/* Enum: FEMALE("FEMALE",0), MALE("MALE",1); Enum: PASSPORT("PASSPORT",0), IDENTITYCARD("IDENTITY CARD",1) */
INSERT INTO USER(USERNAME,REAL_NAME,ENGLISH_NAME,PASSWORD,SEX,ID_NUMBER,ID_NUMBER_TYPE,CURRENT_COUNTRY,CURRENT_CITY) VALUES('email@email.com','Real Name','Cain','password',1,'310229123456789',1,'USA','San Diego');

/* Enum: EMAIL("EMAIL",0), TELEPHONE("TELEPHONE",1), OTHER("OTHER",2) */
INSERT INTO CONTACT(INFO,TYPE,OTHER_DESCRIPTION,USER_ID) VALUES("email@email.com",0,"",1);
INSERT INTO CONTACT(INFO,TYPE,OTHER_DESCRIPTION,USER_ID) VALUES("911",1,"",1);
INSERT INTO CONTACT(INFO,TYPE,OTHER_DESCRIPTION,USER_ID) VALUES("123456",2,"WebChat",1);

/* Enum: Bachelor("BACHELOR",0), Master("MASTER",1), Doctor("DOCTOR",2), PostDoctor("POST-DOCTOR",3), Other("OTHER",4) */
INSERT INTO PERSONAL_HISTORY(UNIVERSITY,UNIVERSITY_DEGREE,GRADUATION_YEAR,USER_ID) VALUES("San Diego State University",2,'2013',1);

/* Enum: Honorary_Title("HONORARY TITLE",0), Thesis("THESIS",1), Intellectual_property("INTELLECTUAL PROPERTY",2), Other("OTHER",3) */
INSERT INTO AWARDS(TYPE,DESCRIPTION,REFERRER,OTHER,USER_ID) VALUES(0,'Captain','Bill','',1);


































