/* DDL FOR DERBY DATABASE */

/*CREATE DATABASE ORANGE;*/

/* DROP TABLE IF THE EXISTS,IGNORE THE ERROR THAT THE TABLE IS NOT EXISTS.*/
DROP TABLE ADDRESS;
DROP TABLE DISTRICT;
DROP TABLE CITY;
DROP TABLE COUNTRY;
DROP TABLE CONTACT_INFO;
DROP TABLE STOCK;
DROP TABLE PRODUCT;
DROP TABLE ORDERED_ITEM;
DROP TABLE PAY;
DROP TABLE USER_ACCOUNT;

CREATE TABLE USER_ACCOUNT (
 ID INT NOT NULL PRIMARY KEY,
 USERNAME VARCHAR(50) NOT NULL UNIQUE,
 PASSWORD VARCHAR(50)
);

CREATE TABLE CONTACT_INFO(
ID INT NOT NULL PRIMARY KEY,
TEL_PHONE VARCHAR(50),
FIXED_LINE_TELEPHONE VARCHAR(50),
FAX VARCHAR(50),
EMAIL VARCHAR(50),
USER_ACCOUNT_ID INT
);

CREATE TABLE ADDRESS (
ID INT NOT NULL PRIMARY KEY,
COUNTRY_ID INT,
CITY_ID INT,
DISTRICT_ID INT,
ZIP_CODE VARCHAR(50),
DETAILED_ADDRESS VARCHAR(100),
USER_ACCOUNT_ID INT
);

CREATE TABLE COUNTRY(
ID INT NOT NULL PRIMARY KEY,
NAME VARCHAR(100)
);

CREATE TABLE CITY(
ID INT NOT NULL PRIMARY KEY,
COUNTRY_ID INT,
NAME VARCHAR(100)
);

CREATE TABLE DISTRICT(
ID INT NOT NULL PRIMARY KEY,
CITY_ID INT,
NAME VARCHAR(100)
);

CREATE TABLE PRODUCT(
ID INT NOT NULL PRIMARY KEY,
NAME VARCHAR(100) NOT NULL UNIQUE,
PRODUCT_TYPE VARCHAR(50),
INFO VARCHAR(50),
PRICE INT,
STOCK_ID INT
);
/* INFO: property key*/

CREATE TABLE STOCK(
ID INT NOT NULL PRIMARY KEY,
QUANTITY INT
);

CREATE TABLE ORDERED_ITEM(
ID INT NOT NULL PRIMARY KEY,
ORDERED_QUANTITY INT,
STATUS INT,
SHOPPING_CART_DATE TIMESTAMP,
ORDERED_DATE TIMESTAMP,
RECEIPT_DATE TIMESTAMP,
PRODUCT_ID INT,
USER_ACCOUNT_ID INT
);
/*Note: '0' indicates that the products in the shopping cart.
		'1' indicates that the products have been bought but the trade is in progress.
		'2' indicates that the products have been bought and trade has completed. */

CREATE TABLE PAY(
ID INT NOT NULL PRIMARY KEY,
BANK_NAME VARCHAR(50),
USER_ACCOUNT_ID INT,
ORDERED_ITEM_ID INT,
TOTAL_PRICE INT
);	

/* CONSTRAINT */
ALTER TABLE CONTACT_INFO ADD CONSTRAINT USER_ACCOUNT_ID_CONTACT_INFO_FK FOREIGN KEY (USER_ACCOUNT_ID) REFERENCES USER_ACCOUNT(ID);
ALTER TABLE ADDRESS ADD CONSTRAINT COUNTRY_ID_ADDRESS_FK FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY(ID);
ALTER TABLE ADDRESS ADD CONSTRAINT CITY_ID_ADDRESS_FK FOREIGN KEY (CITY_ID) REFERENCES CITY(ID);
ALTER TABLE ADDRESS ADD CONSTRAINT DISTRICT_ID_ADDRESS_FK FOREIGN KEY (DISTRICT_ID) REFERENCES DISTRICT(ID);
ALTER TABLE ADDRESS  ADD CONSTRAINT USER_ACCOUNT_ID_ADDRESS_KEY FOREIGN KEY (USER_ACCOUNT_ID) REFERENCES USER_ACCOUNT(ID);
ALTER TABLE CITY ADD CONSTRAINT COUNTRY_ID_CITY_FK FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY(ID);
ALTER TABLE DISTRICT ADD CONSTRAINT CITY_ID_DISTRICT_FK FOREIGN KEY (CITY_ID) REFERENCES CITY(ID);
ALTER TABLE PRODUCT ADD CONSTRAINT STOCK_ID_PRODUCT_FK FOREIGN KEY (STOCK_ID) REFERENCES STOCK(ID);
ALTER TABLE ORDERED_ITEM ADD CONSTRAINT PRODUCT_ID_ORDERED_ITEM_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID);
ALTER TABLE ORDERED_ITEM ADD CONSTRAINT USER_ACCOUNT_ID_ORDERED_ITEM_FK FOREIGN KEY (USER_ACCOUNT_ID) REFERENCES USER_ACCOUNT(ID);
ALTER TABLE PAY ADD CONSTRAINT USER_ACCOUNT_ID_PAY_FK FOREIGN KEY (USER_ACCOUNT_ID) REFERENCES USER_ACCOUNT(ID);
ALTER TABLE PAY ADD CONSTRAINT ORDERED_ITEM_PAY_FK FOREIGN KEY (ORDERED_ITEM_ID) REFERENCES ORDERED_ITEM(ID);
/* CONSTRAINT */

/* END */




















