INSERT INTO USER_ACCOUNT(USERNAME,PASSWORD) VALUES('ORANGE','ORANGE');
INSERT INTO USER_ACCOUNT(USERNAME,PASSWORD) VALUES('APPLE','APPLE');

INSERT INTO CONTACT_INFO(TEL_PHONE,FIXED_LINE_TELEPHONE,FAX,EMAIL,USER_ACCOUNT_ID) VALUES("13355486541","25848971","66488548","apple1@orange.com",1);
INSERT INTO CONTACT_INFO(TEL_PHONE,FIXED_LINE_TELEPHONE,FAX,EMAIL,USER_ACCOUNT_ID) VALUES("13355486542","25848972","66488542","apple2@orange.com",1);
INSERT INTO CONTACT_INFO(TEL_PHONE,FIXED_LINE_TELEPHONE,FAX,EMAIL,USER_ACCOUNT_ID) VALUES("13355486543","25848973","66488543","perl1@orange.com",2);
INSERT INTO CONTACT_INFO(TEL_PHONE,FIXED_LINE_TELEPHONE,FAX,EMAIL,USER_ACCOUNT_ID) VALUES("13355486544","25848974","66488544","perl2@orange.com",2);

INSERT INTO ADDRESS(COUNTRY_CITY_DISTRICT_ZIP_CODE,DETAILED_ADDRESS,USER_ACCOUNT_ID) VALUES();

INSERT INTO COUNTRY(NAME) VALUES();

INSERT INTO CITY(COUNTRY_NAME) VALUES();

INSERT INTO DISTRICT(CITY_NAME) VALUES();

INSERT INTO STOCK(QUANTITY) VALUES(5000);

INSERT INTO PRODUCT(NAME,PRODUCT_TYPE,INFO,PRICE,STOCK_ID) VALUES("ORANGE","Phone","",5000,1);

INSERT INTO ORDERED_ITEM(ORDERED_QUANTITY,STATUS,SHOPPING_CART_DATE,ORDERED_DATE,RECEIPT_DATE,PRODUCT_USER_ACCOUNT_ID) VALUES();

INSERT INTO PAY(BANK_NAME,USER_ACCOUNT_ORDERED_ITEM_TOTAL_PRICE) VALUES();


































